CREATE TABLE IF NOT EXISTS account_books (
    id BIGSERIAL NOT NULL,
    description VARCHAR(255) NOT NULL,
    fiscal_start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    fiscal_end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id)
);
