CREATE TABLE IF NOT EXISTS account_types (
    id BIGSERIAL NOT NULL,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    root_type VARCHAR(255) NOT NULL,
    debit_sign SMALLINT NOT NULL,
    credit_sign SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id),
    CONSTRAINT uq_account_type_code UNIQUE(code) 
);